export default ["activityfill", "crownfill", "crown", "goodsfill", "messagefill", "profilefill", "sound", "sponsorfill",
	"sponsor", "upblock", "weblock", "weunblock", "1111", "my", "myfill", "emojifill", "emojiflashfill",
	"flashbuyfill-copy", "text", "goodsfavor", "musicfill", "musicforbidfill", "roundleftfill", "triangledownfill",
	"triangleupfill", "roundleftfill-copy", "pulldown1", "emojilight", "keyboardlight", "recordfill", "recordlight",
	"appreciate", "record", "check", "roundaddlight", "close", "soundlight", "edit", "cardboardfill", "emoji",
	"cardboard", "favorfill", "formfill", "favor", "coin", "loading", "sortlight", "locationfill", "cardboardforbid",
	"location", "circlefill", "phone", "circle", "roundcheckfill", "attentionforbid", "roundcheck",
	"attentionforbidfill", "roundclosefill", "attentionfavorfill", "roundclose", "attentionfavor", "roundrightfill",
	"piclight", "roundright", "shoplight", "search", "voicelight", "taxi", "attentionfavorfill-copy", "timefill",
	"full", "time", "mail", "unfold", "peoplelist", "warnfill", "goodsnewfill", "warn", "goodsnew", "camerafill",
	"medalfill", "camera", "medal", "commentfill", "newsfill", "comment", "newshotfill", "likefill", "newshot", "like",
	"news", "notificationfill", "videofill", "notification", "video", "order", "askfill", "samefill", "ask", "same",
	"exit", "deliver", "skinfill", "evaluate", "skin", "pay", "moneybagfill", "send", "usefullfill", "shop", "usefull",
	"ticket", "moneybag", "wang", "redpacket_fill", "back", "subscription", "cascades", "home_light", "discover",
	"my_light", "list", "community_light", "more", "cart_light", "scan", "we_light", "settings", "home_fill_light",
	"questionfill", "cart_fill_light", "question", "community_fill_light", "shopfill", "my_fill_light", "form",
	"we_fill_light", "wangfill", "skin_light", "pic", "search_light", "filter", "scan_light", "footprint",
	"people_list_light", "top", "message_light", "pulldown", "close_light", "pullup", "add_light", "right",
	"profile_light", "refresh", "service_light", "moreandroid", "friend_add_light", "deletefill", "edit_light",
	"refund", "camera_light", "cart", "hot_light", "qrcode", "refresh_light", "remind", "back_light", "delete",
	"share_light", "profile", "comment_light", "home", "appreciate_light", "cartfill", "favor_light", "discoverfill",
	"appreciate_fill_light", "homefill", "comment_fill_light", "message", "wang_light", "addressbook",
	"more_android_light", "link", "friend_light", "lock", "more_light", "unlock", "goods_favor_light", "vip",
	"goods_new_fill_light", "weibo", "goods_new_light", "activity", "goods_light", "big", "medal_fill_light",
	"friendaddfill", "medal_light", "friendadd", "news_fill_light", "friendfamous", "news_hot_fill_light", "friend",
	"news_hot_light", "goods", "news_light", "selection", "video_fill_light", "tmall", "message_fill_light", "explore",
	"form_light", "present", "video_light", "squarecheckfill", "search_list_light", "square", "form_fill_light",
	"squarecheck", "global_light", "round", "global", "roundaddfill", "favor_fill_light", "roundadd", "delete_light",
	"add", "back_android", "notificationforbidfill", "back_android_light", "explorefill", "down_light", "fold",
	"round_close_light", "game", "round_close_fill_light", "redpacket", "expressman", "selectionfill", "punch_light",
	"similar", "evaluate_fill", "appreciatefill", "furniture", "infofill", "dress", "info", "coffee", "tao", "sports",
	"mobiletao", "group_light", "forwardfill", "location_light", "forward", "attention_light", "rechargefill",
	"group_fill_light", "recharge", "group_fill", "vipcard", "play_forward_fill", "voice", "subscription_light",
	"voicefill", "deliver_fill", "friendfavor", "notice_forbid_fill", "wifi", "qr_code_light", "share",
	"settings_light", "wefill", "pick", "we", "form_favor_light", "lightauto", "round_comment_light", "lightforbid",
	"phone_light", "lightfill", "round_down_light", "camerarotate", "friend_settings_light", "light", "change",
	"barcode", "round_list_light", "flashlightclose", "ticket_fill", "flashlightopen", "round_friend_fill",
	"searchlist", "round_crown_fill", "service", "round_link_fill", "sort", "round_light_fill", "1212",
	"round_favor_fill", "down", "round_menu_fill", "mobile", "round_location_fill", "mobilefill", "round_pay_fill",
	"copy", "round_like_fill", "countdownfill", "round_people_fill", "countdown", "round_pay", "noticefill",
	"round_rank_fill", "notice", "round_redpacket_fill", "qiang", "round_skin_fill", "upstagefill", "round_record_fill",
	"upstage", "round_ticket_fill", "babyfill", "round_redpacket", "baby", "round_text_fill", "brandfill",
	"round_ticket", "brand", "round_transfer_fill", "choicenessfill", "subtitle_block_light", "choiceness",
	"warn_light", "clothesfill", "round_transfer", "clothes", "vip_code_light", "creativefill",
	"subtitle_unblock_light", "creative", "round_shop_fill", "female", "oppose_fill_light", "keyboard", "oppose_light",
	"male", "living", "newfill", "goods_hot_fill", "new", "ticket_money_fill", "pullleft", "arrow_left_fill",
	"pullright", "arrow_up_fill", "rankfill", "xiaoheiqun", "rank", "auction", "bad", "return", "cameraadd",
	"mall_light", "focus", "mall_fill_light", "friendfill", "broadcast_fill", "cameraaddfill", "at", "apps",
	"card_fill", "paintfill", "paint", "picfill", "refresharrow", "markfill", "mark", "presentfill", "repeal", "album",
	"peoplefill", "people", "servicefill", "repair", "file", "repairfill", "taoxiaopu", "attentionfill", "attention",
	"commandfill", "command", "communityfill", "community", "read", "suan", "hua", "ju", "tian", "calendar", "cut",
	"magic", "backwardfill", "playfill", "stop", "tagfill", "tag", "group", "all", "backdelete", "hotfill", "hot",
	"post", "radiobox", "rounddown", "upload", "writefill", "write", "radioboxfill", "punch", "shake", "add1", "move",
	"safe", "qi", "ye", "cangku", "cangku1",
	"percentage", "select", "cascader", "radio1", "radio2", "checkbox1", "checkbox2", "checkbox3",
	"discount", "number", "color", "json", "text1", "textarea",
	"quyuguanli", "dengji", "jiagoufenxiao", "gudongfenhong", "tixianguanli"
];
